export type Dialect = 'mssql' | 'postgres' | 'sqlite';

export function createAdapters(rawDialect: Dialect) {
  const d = rawDialect.toString().trim().toLowerCase() as Dialect;
  const isMssql = d === 'mssql';
  const isPg = d === 'postgres';

  function colType(mssqlType: string): string {
    if (isMssql) return mssqlType;
    const t = mssqlType.toUpperCase().replace(/\s+/g, ' ').trim();
    if (t === 'BIGINT IDENTITY(1,1)' || t === 'BIGINT IDENTITY')
      return isPg ? 'BIGSERIAL' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
    if (t === 'INT IDENTITY(1,1)' || t === 'INT IDENTITY')
      return isPg ? 'SERIAL' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
    if (t === 'BIGINT') return isPg ? 'BIGINT' : 'INTEGER';
    if (t === 'INT') return 'INTEGER';
    if (t === 'TINYINT') return isPg ? 'SMALLINT' : 'INTEGER';
    if (t === 'SMALLINT') return 'SMALLINT';
    if (t === 'NVARCHAR(MAX)' || t === 'NTEXT' || t === 'NVARCHAR(max)')
      return 'TEXT';
    if (t === 'DATETIMEOFFSET') return isPg ? 'TIMESTAMPTZ' : 'TEXT';
    if (t === 'DATETIME' || t === 'DATE') return mssqlType;
    if (t === 'BIT') return isPg ? 'BOOLEAN' : 'INTEGER';
    if (t === 'FLOAT') return isPg ? 'FLOAT' : 'REAL';
    if (t.startsWith('NVARCHAR(')) {
      const match = mssqlType.match(/NVARCHAR\((\d+)\)/i);
      return isPg ? `VARCHAR(${match?.[1] || '256'})` : 'TEXT';
    }
    return mssqlType;
  }

  return {
    colType,
    quote: (col: string) => (isMssql ? `[${col}]` : `"${col}"`),
    now: (): string =>
      isMssql ? 'GETDATE()' : isPg ? 'NOW()' : "datetime('now')",
    idCol: isMssql
      ? 'IDENTITY(1,1)'
      : isPg
        ? 'GENERATED BY DEFAULT AS IDENTITY'
        : '',
    pk: d === 'sqlite' ? 'PRIMARY KEY AUTOINCREMENT' : 'PRIMARY KEY',
    ref: (t: string, c: string) =>
      isMssql ? `REFERENCES ${t}([${c}])` : `REFERENCES ${t}("${c}")`,
    ns: (s: string) => (isMssql ? `N'${s}'` : `'${s}'`),
    bracketSql: (sql: string) =>
      isMssql ? sql : sql.replace(/\[/g, '"').replace(/\]/g, '"'),
    createTableSql: (
      tableName: string,
      columns: string,
      ifNotExists: boolean,
    ): string => {
      let cols = columns;
      if (!isMssql) {
        cols = cols.replace(
          /^(\s*(?:[a-zA-Z_]\w*|\[[^\]]*\]|"[^"]*")\s+)(\w+(?:\s*\([^)]*\))?)/gim,
          (_, prefix, type) => prefix + colType(type),
        );
      }
      const sql = `CREATE TABLE ${tableName} (\n${cols}\n)`;
      if (isMssql && ifNotExists)
        return `IF OBJECT_ID('${tableName}', 'U') IS NULL\nBEGIN\n${sql}\nEND`;
      if (ifNotExists)
        return sql.replace(/^CREATE\s+TABLE/i, 'CREATE TABLE IF NOT EXISTS');
      return sql;
    },
    dropTableSql: (tableName: string): string =>
      isMssql
        ? `IF OBJECT_ID('${tableName}', 'U') IS NOT NULL\nDROP TABLE ${tableName}`
        : `DROP TABLE IF EXISTS ${tableName}`,
    addColumnSql: (
      table: string,
      column: string,
      rawType: string,
      nullable: boolean,
      defaultValue?: string,
      constraint?: string,
    ): string => {
      const mappedType = colType(rawType);
      const nullStr = nullable ? 'NULL' : 'NOT NULL';
      const defStr = defaultValue ? ` DEFAULT ${defaultValue}` : '';
      const constrStr = constraint ? ` ${constraint}` : '';
      const q = (s: string) => (isMssql ? `[${s}]` : `"${s}"`);
      if (isMssql)
        return `ALTER TABLE ${table} ADD ${q(column)} ${mappedType} ${nullStr}${defStr}${constrStr}`;
      if (isPg)
        return `ALTER TABLE "${table}" ADD COLUMN "${column}" ${mappedType} ${nullStr}${defStr}${constrStr}`;
      return `ALTER TABLE ${table} ADD COLUMN ${column} ${mappedType} ${nullStr}${defStr}${constrStr}`;
    },
    executeRawSql: (sql: string): string =>
      isMssql ? sql : sql.replace(/\[/g, '"').replace(/\]/g, '"'),
    top: (n: number, selectSql: string): string =>
      isMssql
        ? `SELECT TOP ${n} ${selectSql.slice(7)}`
        : `${selectSql} LIMIT ${n}`,
    fkConstraint: (name: string, table: string, column: string): string =>
      isMssql
        ? `CONSTRAINT ${name} FOREIGN KEY REFERENCES ${table}([${column}])`
        : `FOREIGN KEY REFERENCES ${table}("${column}")`,
    alterColumnSql: (
      table: string,
      column: string,
      rawType: string,
      nullable: boolean,
    ): string => {
      const mappedType = colType(rawType);
      const nullStr = nullable ? 'NULL' : 'NOT NULL';
      const q = (s: string) => (isMssql ? `[${s}]` : `"${s}"`);
      return `ALTER TABLE ${table} ALTER COLUMN ${q(column)} ${mappedType} ${nullStr}`;
    },
  };
}

export type Adapters = ReturnType<typeof createAdapters>;
