import {
  ZTCurrency,
  ZTCurrencyHistory,
  ZTCompany,
  ZTDeviceType,
  ZTDeviceStatus,
  ZTContractStatus,
  ZTContractPeriodStatus,
  ZTContract,
  ZTContractPeriod,
  ZTContractPeriodDevicePrice,
  ZTDevice,
  ZTManufacturer,
  ZTMarketer,
  ZTDeviceSalePrice,
  ZTDeviceSale,
  ZTCommissionSettlement,
  ZTCommissionType,
  ZTCommissionSettlementStatus,
  ZTInventoryStatus,
} from '@rahino/localdatabase/models';

export const zootagModels = [
  ZTCurrency,
  ZTCurrencyHistory,
  ZTCompany,
  ZTDeviceType,
  ZTDeviceStatus,
  ZTContractStatus,
  ZTContractPeriodStatus,
  ZTContract,
  ZTContractPeriod,
  ZTContractPeriodDevicePrice,
  ZTDevice,
  ZTManufacturer,
  ZTMarketer,
  ZTDeviceSalePrice,
  ZTDeviceSale,
  ZTCommissionSettlement,
  ZTCommissionType,
  ZTCommissionSettlementStatus,
  ZTInventoryStatus,
];
